"""Added manager_feedbacks relationship

Revision ID: e785dfb6ab86
Revises: 8f151a88ebd7
Create Date: 2025-02-20 14:34:50.159284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e785dfb6ab86'
down_revision: Union[str, None] = '8f151a88ebd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
